const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const { Ollama } = require('ollama');
const { translateFromEnglish } = require('./translationService');

const ollama = new Ollama({ host: 'http://localhost:11434' });
const HINDI_TRANSLATIONS = {
  'FIRST INFORMATION REPORT (FIR)': 'प्राथमिकी (FIR)',
  'Under Section 154 Cr.P.C.': 'धारा 154 सीआरपीसी के तहत',
  'Police Station': 'थाना',
  'District': 'जिला',
  'FIR No.': 'प्राथमिकी संख्या',
  'Date': 'तारीख',
  'COMPLAINANT DETAILS': 'शिकायतकर्ता का विवरण',
  'Name': 'नाम',
  'Address': 'पता',
  'Contact Number': 'संपर्क नंबर',
  'INCIDENT DETAILS': 'घटना का विवरण',
  'Date of Incident': 'घटना की तारीख',
  'Time of Incident': 'घटना का समय',
  'Location of Incident': 'घटना का स्थान',
  'Type of Harassment': 'उत्पीड़न का प्रकार',
  'ACCUSED DETAILS': 'आरोपी का विवरण',
  'Description': 'विवरण',
  'DETAILED DESCRIPTION OF INCIDENT': 'घटना का विस्तृत विवरण',
  'WITNESSES': 'गवाह',
  'EVIDENCE/DOCUMENTS': 'साक्ष्य/दस्तावेज़',
  'Applicable Sections:': 'लागू धाराएं:',
  'Section 354A IPC - Sexual Harassment': 'धारा 354A आईपीसी - यौन उत्पीड़न',
  'POSH Act 2013 - Prevention of Sexual Harassment at Workplace': 'पोश अधिनियम 2013 - कार्यस्थल पर यौन उत्पीड़न की रोकथाम',
  'Section 509 IPC - Word, gesture or act intended to insult modesty': 'धारा 509 आईपीसी - शब्द, इशारा या कृत्य जिससे महिला की शालीनता को अपमानित करने का इरादा हो',
  'Complainant Signature': 'शिकायतकर्ता के हस्ताक्षर',
  'Received by (Police Officer)': 'प्राप्तकर्ता (पुलिस अधिकारी)',
  'Rank': 'पद',
  'Date & Time': 'तारीख और समय',
  'Note: This is a draft FIR generated by Legal Lens AI Assistant. Please review and complete all details before submission to authorities.': 'नोट: यह लीगल लेंस एआई सहायक द्वारा तैयार की गई एक मसौदा प्राथमिकी है। अधिकारियों को सबमिट करने से पहले कृपया सभी विवरणों की समीक्षा करें और पूरा करें।',
  'Not Provided': 'प्रदान नहीं किया गया',
  'None': 'कोई नहीं',
  'Workplace Harassment': 'कार्यस्थल उत्पीड़न'
};
async function extractFIRDetails(chatHistory) {
  const conversationText = chatHistory
    .map(msg => `${msg.role}: ${msg.text}`)
    .join('\n');

  const extractionPrompt = `You are a legal assistant helping to extract information for filing an FIR (First Information Report) in India.

From the following conversation, extract these details in JSON format:
1. complainant_name: Name of the person filing complaint (if mentioned, else "Not Provided")
2. complainant_address: Address of complainant (if mentioned, else "Not Provided")
3. complainant_phone: Phone number (if mentioned, else "Not Provided")
4. incident_date: Date of incident (if mentioned, else "Not Provided")
5. incident_time: Time of incident (if mentioned, else "Not Provided")
6. incident_location: Where did incident occur (if mentioned, else "Not Provided")
7. accused_name: Name of accused person (if mentioned, else "Not Provided")
8. accused_description: Physical description of accused (if mentioned, else "Not Provided")
9. incident_description: Detailed description of what happened
10. witnesses: Any witness names (if mentioned, else "None")
11. evidence: Any evidence mentioned (if mentioned, else "None")
12. harassment_type: Type of harassment (sexual, physical, verbal, etc.)

Conversation:
${conversationText}

Return ONLY a valid JSON object with the above fields. Do not include any other text.`;

  try {
    const response = await ollama.chat({
      model: 'llama3.2:1b',
      messages: [{ role: 'user', content: extractionPrompt }],
      stream: false,
      options: {
        temperature: 0.1, // Low temperature for precise extraction
        num_predict: 800
      }
    });

    // Extract JSON from response
    const jsonMatch = response.message.content.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      return JSON.parse(jsonMatch[0]);
    }

    // Fallback: Create basic structure from conversation
    return {
      complainant_name: "Not Provided",
      complainant_address: "Not Provided",
      complainant_phone: "Not Provided",
      incident_date: new Date().toLocaleDateString('en-IN'),
      incident_time: "Not Provided",
      incident_location: "Not Provided",
      accused_name: "Not Provided",
      accused_description: "Not Provided",
      incident_description: conversationText.substring(0, 500),
      witnesses: "None",
      evidence: "None",
      harassment_type: "Workplace Harassment"
    };
  } catch (error) {
    console.error('Error extracting FIR details:', error);
    throw error;
  }
}

/**
 * Generate FIR PDF document with language support
 */
async function generateFIRPDF(firDetails, outputPath, language = 'en') {
  return new Promise(async (resolve, reject) => {
    try {
      const doc = new PDFDocument({ 
        size: 'A4', 
        margins: { top: 50, bottom: 50, left: 50, right: 50 } 
      });
      const stream = fs.createWriteStream(outputPath);

      doc.pipe(stream);

      // Set font based on language
      const fontPath = path.join(__dirname, '../fonts');
      const fontMapping = {
        'hi': 'NotoSansDevanagari-Regular.ttf',  // Hindi
        'mr': 'NotoSansDevanagari-Regular.ttf',  // Marathi (uses Devanagari)
        'ta': 'NotoSansTamil-Regular.ttf',       // Tamil
        'te': 'NotoSansTelugu-Regular.ttf',      // Telugu
        'bn': 'NotoSansBengali-Regular.ttf',     // Bengali
        'gu': 'NotoSansGujarati-Regular.ttf',    // Gujarati
        'kn': 'NotoSansKannada-Regular.ttf',     // Kannada
        'ml': 'NotoSansMalayalam-Regular.ttf',   // Malayalam
        'pa': 'NotoSansGurmukhi-Regular.ttf'     // Punjabi
      };

      // Try to load language-specific font, fallback to Helvetica
      if (language !== 'en' && fontMapping[language]) {
        const fontFile = path.join(fontPath, fontMapping[language]);
        if (fs.existsSync(fontFile)) {
          doc.registerFont('RegionalFont', fontFile);
          doc.font('RegionalFont');
          console.log(`✅ Using ${fontMapping[language]} for ${language}`);
        } else {
          console.warn(`⚠️ Font not found: ${fontFile}. Using Helvetica (English font). Hindi/regional text may not display correctly.`);
          console.warn(`📥 Please download fonts using: FONT_INSTALLATION_GUIDE.md`);
          doc.font('Helvetica');
        }
      } else {
        doc.font('Helvetica');
      }

      // Helper function to get translated text
      const t = async (text) => {
        if (language === 'hi') {
          // Use pre-defined translations for headings
          if (HINDI_TRANSLATIONS[text]) {
            return HINDI_TRANSLATIONS[text];
          }
          // For dynamic content, translate using the service
          try {
            return await translateFromEnglish(text, 'hi');
          } catch (err) {
            console.warn('Translation failed, using original:', err.message);
            return text;
          }
        }
        return text;
      };

      // Translate all FIR details to Hindi if needed
      let translatedDetails = { ...firDetails };
      if (language === 'hi') {
        translatedDetails = {
          complainant_name: firDetails.complainant_name === 'Not Provided' ? 
            await t('Not Provided') : firDetails.complainant_name,
          complainant_address: firDetails.complainant_address === 'Not Provided' ? 
            await t('Not Provided') : await t(firDetails.complainant_address),
          complainant_phone: firDetails.complainant_phone,
          incident_date: firDetails.incident_date,
          incident_time: firDetails.incident_time === 'Not Provided' ? 
            await t('Not Provided') : firDetails.incident_time,
          incident_location: firDetails.incident_location === 'Not Provided' ? 
            await t('Not Provided') : await t(firDetails.incident_location),
          accused_name: firDetails.accused_name === 'Not Provided' ? 
            await t('Not Provided') : firDetails.accused_name,
          accused_description: firDetails.accused_description === 'Not Provided' ? 
            await t('Not Provided') : await t(firDetails.accused_description),
          incident_description: await t(firDetails.incident_description),
          witnesses: firDetails.witnesses === 'None' ? 
            await t('None') : await t(firDetails.witnesses),
          evidence: firDetails.evidence === 'None' ? 
            await t('None') : await t(firDetails.evidence),
          harassment_type: await t(firDetails.harassment_type)
        };
      }

      // Header
      doc.fontSize(20)
         .font('Helvetica-Bold')
         .text(await t('FIRST INFORMATION REPORT (FIR)'), { align: 'center' })
         .moveDown(0.5);

      doc.fontSize(12)
         .font('Helvetica')
         .text(await t('Under Section 154 Cr.P.C.'), { align: 'center' })
         .moveDown(1);

      // Add line
      doc.moveTo(50, doc.y)
         .lineTo(545, doc.y)
         .stroke()
         .moveDown(1);

      // Police Station details
      const policeStationLabel = await t('Police Station');
      const districtLabel = await t('District');
      const firNoLabel = await t('FIR No.');
      const dateLabel = await t('Date');
      
      doc.fontSize(11)
         .font('Helvetica-Bold')
         .text(`${policeStationLabel}: ___________________________________`)
         .moveDown(0.5)
         .text(`${districtLabel}: ___________________________________`)
         .moveDown(0.5)
         .text(`${firNoLabel}: ___________ ${dateLabel}: ` + new Date().toLocaleDateString('en-IN'))
         .moveDown(1.5);

      // Section 1: Complainant Details
      doc.fontSize(13)
         .font('Helvetica-Bold')
         .fillColor('#667eea')
         .text(`1. ${await t('COMPLAINANT DETAILS')}`, { underline: true })
         .fillColor('black')
         .moveDown(0.5);

      doc.fontSize(10)
         .font('Helvetica')
         .text(`${await t('Name')}: ${translatedDetails.complainant_name}`, { indent: 20 })
         .moveDown(0.3)
         .text(`${await t('Address')}: ${translatedDetails.complainant_address}`, { indent: 20 })
         .moveDown(0.3)
         .text(`${await t('Contact Number')}: ${translatedDetails.complainant_phone}`, { indent: 20 })
         .moveDown(1);

      // Section 2: Incident Details
      doc.fontSize(13)
         .font('Helvetica-Bold')
         .fillColor('#667eea')
         .text(`2. ${await t('INCIDENT DETAILS')}`, { underline: true })
         .fillColor('black')
         .moveDown(0.5);

      doc.fontSize(10)
         .font('Helvetica')
         .text(`${await t('Date of Incident')}: ${translatedDetails.incident_date}`, { indent: 20 })
         .moveDown(0.3)
         .text(`${await t('Time of Incident')}: ${translatedDetails.incident_time}`, { indent: 20 })
         .moveDown(0.3)
         .text(`${await t('Location of Incident')}: ${translatedDetails.incident_location}`, { indent: 20 })
         .moveDown(0.3)
         .text(`${await t('Type of Harassment')}: ${translatedDetails.harassment_type}`, { indent: 20 })
         .moveDown(1);

      // Section 3: Accused Details
      doc.fontSize(13)
         .font('Helvetica-Bold')
         .fillColor('#667eea')
         .text(`3. ${await t('ACCUSED DETAILS')}`, { underline: true })
         .fillColor('black')
         .moveDown(0.5);

      doc.fontSize(10)
         .font('Helvetica')
         .text(`${await t('Name')}: ${translatedDetails.accused_name}`, { indent: 20 })
         .moveDown(0.3)
         .text(`${await t('Description')}: ${translatedDetails.accused_description}`, { indent: 20 })
         .moveDown(1);

      // Section 4: Incident Description
      doc.fontSize(13)
         .font('Helvetica-Bold')
         .fillColor('#667eea')
         .text(`4. ${await t('DETAILED DESCRIPTION OF INCIDENT')}`, { underline: true })
         .fillColor('black')
         .moveDown(0.5);

      doc.fontSize(10)
         .font('Helvetica')
         .text(translatedDetails.incident_description, { 
           indent: 20, 
           align: 'justify',
           lineGap: 3
         })
         .moveDown(1);

      // Section 5: Witnesses
      doc.fontSize(13)
         .font('Helvetica-Bold')
         .fillColor('#667eea')
         .text(`5. ${await t('WITNESSES')}`, { underline: true })
         .fillColor('black')
         .moveDown(0.5);

      doc.fontSize(10)
         .font('Helvetica')
         .text(translatedDetails.witnesses, { indent: 20 })
         .moveDown(1);

      // Section 6: Evidence
      doc.fontSize(13)
         .font('Helvetica-Bold')
         .fillColor('#667eea')
         .text(`6. ${await t('EVIDENCE/DOCUMENTS')}`, { underline: true })
         .fillColor('black')
         .moveDown(0.5);

      doc.fontSize(10)
         .font('Helvetica')
         .text(translatedDetails.evidence, { indent: 20 })
         .moveDown(1.5);

      // Add line
      doc.moveTo(50, doc.y)
         .lineTo(545, doc.y)
         .stroke()
         .moveDown(1);

      // Legal sections
      doc.fontSize(11)
         .font('Helvetica-Bold')
         .text(await t('Applicable Sections:'), { underline: true })
         .moveDown(0.5)
         .font('Helvetica')
         .text(`• ${await t('Section 354A IPC - Sexual Harassment')}`, { indent: 20 })
         .text(`• ${await t('POSH Act 2013 - Prevention of Sexual Harassment at Workplace')}`, { indent: 20 })
         .text(`• ${await t('Section 509 IPC - Word, gesture or act intended to insult modesty')}`, { indent: 20 })
         .moveDown(1.5);

      // Signature section
      doc.moveTo(50, doc.y)
         .lineTo(545, doc.y)
         .stroke()
         .moveDown(1);

      doc.fontSize(10)
         .text(`${await t('Complainant Signature')}: _________________________`, { indent: 20 })
         .moveDown(0.5)
         .text(`${await t('Date')}: _________________________`, { indent: 20 })
         .moveDown(1.5);

      doc.text(`${await t('Received by (Police Officer)')}: _________________________`, { indent: 20 })
         .moveDown(0.5)
         .text(`${await t('Rank')}: _________________________`, { indent: 20 })
         .moveDown(0.5)
         .text(`${await t('Date & Time')}: _________________________`, { indent: 20 });

      // Footer
      doc.fontSize(8)
         .moveDown(2)
         .fillColor('#666')
         .text(await t('Note: This is a draft FIR generated by Legal Lens AI Assistant. Please review and complete all details before submission to authorities.'), {
           align: 'center',
           italic: true
         })
         .fillColor('black');

      // Finalize PDF
      doc.end();

      stream.on('finish', () => {
        console.log('✅ FIR PDF generated successfully:', outputPath);
        resolve(outputPath);
      });

      stream.on('error', (error) => {
        console.error('❌ Error generating FIR PDF:', error);
        reject(error);
      });

    } catch (error) {
      console.error('❌ Error creating PDF:', error);
      reject(error);
    }
  });
}

/**
 * Main function to generate FIR from chat history with language support
 */
async function generateFIRFromChat(chatHistory, userId = 'user', language = 'en', previewOnly = false) {
  try {
    console.log(`📝 Extracting FIR details from chat...${previewOnly ? ' (Preview Mode)' : ''}`);
    const firDetails = await extractFIRDetails(chatHistory);
    
    // If preview only, return just the details without generating PDF
    if (previewOnly) {
      return {
        success: true,
        details: firDetails,
        language
      };
    }

    console.log(`📄 Generating FIR PDF in ${language === 'hi' ? 'Hindi' : 'English'}...`);
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').split('T')[0];
    const langSuffix = language === 'hi' ? '_Hindi' : '';
    const filename = `FIR_Draft_${userId}_${timestamp}_${Date.now()}${langSuffix}.pdf`;
    const outputPath = path.join(__dirname, '../data', filename);

    // Ensure data directory exists
    const dataDir = path.join(__dirname, '../data');
    if (!fs.existsSync(dataDir)) {
      fs.mkdirSync(dataDir, { recursive: true });
    }

    await generateFIRPDF(firDetails, outputPath, language);

    return {
      success: true,
      filename,
      path: outputPath,
      details: firDetails,
      language
    };
  } catch (error) {
    console.error('❌ Error generating FIR:', error);
    throw error;
  }
}

module.exports = {
  extractFIRDetails,
  generateFIRPDF,
  generateFIRFromChat
};
